version: 2
updates:
  # Update npm dependencies (React Native, Expo, Node.js)
  - package-ecosystem: "npm"
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "your-github-username"

  # Update GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory
    schedule:
      interval: "weekly"
